### PR TITLE
2021 Updates

### PR DESCRIPTION
**Pull request by mythmon**
- Remove automatic geoip database download
- Update to Rust 1.52 and fix clippy lints
- Update to actix-web 2
- Update to actix-web 3
- Update remaining crates

### CODE REVIEW

**Comment by mythmon** [comment]
@jrconlin Can I tag you for review again here? This time I expect `bors merge` will work.

bors delegate= @jrconlin

**Comment by mythmon** [comment]
Ah, I'll need to figure out how to get a Maxmind database in the tests. That's a problem for next week.

**Comment by jrconlin** [comment]
So...
One of the ways that I've "solved" this in the past is that there are older versions of the database out there that are not subject to the current licensing restrictions. Ones that are over 3 years old should be good. The database itself is proprietary so "faking" one is considerably difficult. 

The alternate approach is to mock the return results from a maxmind query using a setting flag.

**Comment by mythmon** [comment]
@jrconlin ok, I think this is ready for re-review. Using the API key here is a little weird, since it relies on my own (mozilla-email) Maxmind account. That should be fine, and it is what we have done on Normandy for a while. I feel better about that than about using a really old version of the database.

**Comment by mythmon** [comment]
@jrconlin friendly reminder this PR is ready for review. Of course the Contile launch should take precedence over this. I just wanted to make sure it is still on your list.

**Review by jrconlin — APPROVED** [review]
Sorry, finally got a chance to go through this one.

**Comment by mythmon** [comment]
Thanks for the review. No worries about the delay. 🙂 

bors r= @jrconlin

**Pull request merged**
