### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by smarnach**
The only step that required substantial changes was upgrading actix-web. I followed the migration guide at https://github.com/actix/actix-web/blob/master/actix-web/MIGRATION-4.0.md.

The old version included both tokio 0.x and 1.x in the dependency graph, which are known to not work together. With this PR, tokio get included only a single time.

### CODE REVIEW

**Comment by smarnach** [comment]
This PR resolves the following security advisories (`cargo audit` output for the current master branch):
```
Crate:         actix-http
Version:       2.2.0
Title:         Potential request smuggling capabilities due to lack of input validation
Date:          2021-06-16
ID:            RUSTSEC-2021-0081
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0081
Solution:      Upgrade to ^2.2.1 OR >=3.0.0-beta.9
Dependency tree: 
actix-http 2.2.0
├── awc 2.0.3
│   └── actix-web 3.3.2
│       └── classify-client 0.2.0
└── actix-web 3.3.2

Crate:         brotli-sys
Version:       0.3.2
Title:         Integer overflow in the bundled Brotli C library
Date:          2021-12-20
ID:            RUSTSEC-2021-0131
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0131
Solution:      No safe upgrade is available!
Dependency tree: 
brotli-sys 0.3.2
└── brotli2 0.3.2
    └── actix-http 2.2.0
        ├── awc 2.0.3
        │   └── actix-web 3.3.2
        │       └── classify-client 0.2.0
        └── actix-web 3.3.2

Crate:         regex
Version:       1.5.4
Title:         Regexes with large repetitions on empty sub-expressions take a very long time to parse
Date:          2022-03-08
ID:            RUSTSEC-2022-0013
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution:      Upgrade to >=1.5.5
Dependency tree: 
regex 1.5.4
├── classify-client 0.2.0
├── actix-web 3.3.2
│   └── classify-client 0.2.0
├── actix-router 0.2.7
│   └── actix-web 3.3.2
└── actix-http 2.2.0
    ├── awc 2.0.3
    │   └── actix-web 3.3.2
    └── actix-web 3.3.2

Crate:         thread_local
Version:       1.1.3
Title:         Data race in `Iter` and `IterMut`
Date:          2022-01-23
ID:            RUSTSEC-2022-0006
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution:      Upgrade to >=1.1.4
Dependency tree: 
thread_local 1.1.3
├── slog-term 2.8.0
│   └── classify-client 0.2.0
└── slog-async 2.6.0
    └── classify-client 0.2.0

Crate:         tokio
Version:       0.2.25
Title:         Data race when sending and receiving after closing a `oneshot` channel
Date:          2021-11-16
ID:            RUSTSEC-2021-0124
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0124
Solution:      Upgrade to >=1.8.4, <1.9.0 OR >=1.13.1
Dependency tree: 
tokio 0.2.25

Crate:         tokio
Version:       1.5.0
Title:         Task dropped in wrong thread when aborting `LocalSet` task
Date:          2021-07-07
ID:            RUSTSEC-2021-0072
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0072
Solution:      Upgrade to >=1.5.1, <1.6.0 OR >=1.6.3, <1.7.0 OR >=1.7.2, <1.8.0 OR >=1.8.1
Dependency tree: 
tokio 1.5.0

Crate:         tokio
Version:       1.5.0
Title:         Data race when sending and receiving after closing a `oneshot` channel
Date:          2021-11-16
ID:            RUSTSEC-2021-0124
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0124
Solution:      Upgrade to >=1.8.4, <1.9.0 OR >=1.13.1

Crate:         net2
Version:       0.2.37
Warning:       unmaintained
Title:         `net2` crate has been deprecated; use `socket2` instead
Date:          2020-05-01
ID:            RUSTSEC-2020-0016
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree: 
net2 0.2.37
├── miow 0.2.2
└── mio 0.6.23

Crate:         stdweb
Version:       0.4.20
Warning:       unmaintained
Title:         stdweb is unmaintained
Date:          2020-05-04
ID:            RUSTSEC-2020-0056
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0056
Dependency tree: 
stdweb 0.4.20
└── time 0.2.26

Crate:         crossbeam-utils
Version:       0.8.4
Warning:       yanked
Dependency tree: 
crossbeam-utils 0.8.4
└── crossbeam-channel 0.5.1
    ├── slog-async 2.6.0
    │   └── classify-client 0.2.0
    ├── cadence 0.25.0
    │   └── classify-client 0.2.0
    └── actix 0.11.1
        └── classify-client 0.2.0

Crate:         pin-project
Version:       0.4.28
Warning:       yanked
Dependency tree: 
pin-project 0.4.28
```

**Review by leplatrem — APPROVED** [review]
test result: ok. 17 passed;

**Review by pjenvey — APPROVED** [review]

**Comment by smarnach** [comment]
Thanks for the reviews!

**Comment by smarnach** [comment]
Something's weird here. CircleCI did run and completed successfully, but somehow did not report the status back. I changed the branch protection rules [following the troubleshooting docs for CircleCI](https://circleci.com/docs/2.0/enable-checks/#troubleshooting-github-checks-waiting-for-status-in-github), but Bors still doesn't seem to be happy. I think I'll do a dummy rebase and a force push to get Circle CI running another time.

**Comment by smarnach** [comment]
This didn't change anything, and it looks like I followed the wrong documentation anyway. The docs are for GitHub Checks, but we use GitHub status updates on this repo, which apparently is something completely different, so I'll restore the branch protection settings.

**Comment by smarnach** [comment]
I tried regenerating the Circle CI deploy key, but that didn't have any effect. I then completely disabled Circle CI by clicking the "Stop building" button in the Circle CI project settings, and the set up the project again. Now the status gets reported fine again, and all settings are back to there original values.

**Pull request merged**
