### PR TITLE
License under MPLv2

### PR DESCRIPTION
**Pull request by mythmon**

### CODE REVIEW

**Comment by mythmon** [comment]
@leplatrem and @sciurus, you both have contributed code to the repository, so it would be good to get both of you to approve this before merging.

**Comment by leplatrem** [comment]
I was once told that with MPL each source file has to have a header. For me that has always been annoying enough to use other licenses.

Otherwise, I'm +1 on any license.

**Comment by sciurus** [comment]
I am happy to license my contributions under the MPLv2.

Have you verified that all the crates you're using have a license that is compatible with the MPLv2?

**Comment by mythmon** [comment]
> I was once told that with MPL each source file has to have a header. For me that has always been annoying enough that I prefer to use other licenses.

The MPL contains this text:

> If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

I do not find it desirable to put a notice in each file, and I believe it is likely that users of Github will look for a LICENSE file in the root of the project.

> Have you verified that all the crates you're using have a license that is compatible with the MPLv2?

My reading of the MPLv2 (and most other non-GPL open source licenses) does not require dependencies such as crates to be under a compatible license, since we are not distributing those crates as a part of this repository. Since we are only linking to them, they only need to be in a form such that any user of the software could reasonably access them. Being published on crates.io seems like a reasonable enough form of access. If we were vendoring the libraries, I think we would need to care about the license status of the crates, but we aren't doing that.

**Pull request merged**
